apiVersion: v1
kind: Service
metadata:
  name: mysql-crud-app
  labels:
    app: mysql-crud-app
spec:
  selector:
    app: mysql-crud-app
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP

---