apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
      - name: crud-app
        image: vikendu/crud-app:1.2.3
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /users
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /users
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 5

---